### ISSUE TITLE
Super Demo

### ISSUE THREAD

**Issue by andreipet** [ZuBsPaCe/unity-smooth-movement-test#1]
This demo should be embedded in Unity.
A super job.
10x.

**Comment by ZuBsPaCe** [comment]
Thank you @andreipet . Your feedback means a lot to me!

I now finished the chapter about [manual physic updates](https://www.zubspace.com/blog/smooth-movement-in-unity#part-3-physic2d-simulate) in the related blog post. Maybe you or others can use some of my takeaways in there.

There are also a few tiny fixes and code clean-ups in the [test application](https://www.zubspace.com/tools/smooth-movement-test) regarding Physic2D.Simulate().

Thank you again and happy coding!
